modLoader="javafml"
loaderVersion="[43,)"
license="GNU_GPL.3"
[[mods]]
modId="todecoins"
version="1.19.2-0.0.9"
displayName="Tode Coins"
logoFile="logo.png"
credits="Shout out to the Iron Knight for supporting all the projects I get myself into!"
authors="Warren Tode (ToadieOdie)"
description='''
Adds currency and a banker villager with trades to the game.
'''
[[dependencies.todecoins]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.todecoins]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
